#!/bin/bash

cd /
git init
git remote add origin https://github.com/zsh4k0/comfy.git
git config core.sparseCheckout true
echo "/*" > .git/info/sparse-checkout
git fetch origin
git checkout origin/main -- .
cd /scripts/
./main.sh 